### ISSUE TITLE
mypy plugin fails on Immutable class with Immutable members

### ISSUE THREAD

**Issue by suned** [suned/pfun#22]
```python
from pfun import Immutable

class C(Immutable):
    pass

class B(Immutable):
    c: C
```

error:
```
Traceback (most recent call last):
  File "mypy/semanal.py", line 4626, in accept
  File "mypy/nodes.py", line 927, in accept
  File "mypy/semanal.py", line 1022, in visit_class_def
  File "mypy/semanal.py", line 1093, in analyze_class
  File "mypy/semanal.py", line 1102, in analyze_class_body_common
  File "mypy/semanal.py", line 1162, in apply_class_plugin_hooks
  File "/Users/sune/pfun/pfun/mypy_plugin.py", line 207, in _immutable_hook
    transformer.transform()
  File "mypy/plugins/dataclasses.py", line 90, in transform
  File "mypy/semanal.py", line 4360, in defer
AssertionError: Must not defer during final iteration
```

**Comment by suned** [comment]
Fixed with mypy 0.782
